### PR TITLE
HTML/CSS & JavaScript capstone project - Deploy

### PR DESCRIPTION
**Pull request by Allenkeys**
## Project requirements

- Implement the section "Featured speakers" with dynamic HTML.
- Deploy the project and check to make sure everything works as planned.
- Record a video describing your project.
- Create a good README and pull request description.

### CODE REVIEW

**Review by cynthiainga — CHANGES_REQUESTED** [review]
Hi @Allenkeys, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights

- [ ] No linters errors ✔️ 
- [ ] Descriptive PR ✔️ 
- [ ] Correct Github flow ✔️ 

## Required Changes ♻️

- [ ] Good implementation of the footer on your both pages 👍 , but you still have an issue to fix like color. As required the Fotter of the `About page` should have a dark background in desktop Size 🙃

Screen Shot 2022-09-16 at 14 09 27

- [ ] I noticed that in your Desktop version on the `About page` in the navigation panel there is no link to the home page, so it's difficult for the user to go to the `Home page` when users are navigating in the `About page`. Please kindly fix that.

Screen Shot 2022-09-16 at 14 39 13

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Allenkeys** [comment]
> 

Thank you @cynthiainga for the feedback :+1: 

Before I proceed with any changes, please I would like if you go over this:
- Interactions
  - Links
     - The home page should have a link in the menu to the about page.
     - The logo in the header links to the home page.
     - As required I only added the link to "home" in the mobile version.

-Navbar
  - The background color is consistent and identical as the instruction.
Please, I anticipate your response soon.

**Comment by cynthiainga** [comment]
Hi @Allenkeys,

- [ ] For the links, yes what you mention is true. I suggested you this change because not everyone will know that the logo directs to the home page, it's better that the nav bar also has a link that can direct you to the home page so that the users will find themselves easily when they navigate on your website 🙃 🙃 
- [ ] For the second point about the color, is for the footer, not the navigation bar, I'm so sorry to confuse it. As you can see in the design the footer of the `About page` has a dark background color and the footer of the `Home page` has a white background color, sorry for that let me edit my comment 😊 😊

**Review by Qoosim — APPROVED** [review]
# *Status: Approved* :tada:

Hi @Allenkeys, 

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

## Top Highlights

-   No linter errors. :heavy_check_mark:
-   Good README file. :heavy_check_mark:
-   Correct GitHub Flow. :heavy_check_mark: 
-   Good UI Design. :heavy_check_mark:
-    Meaningful commit messages. :heavy_check_mark:


Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Pull request merged**
